name: publish

on:
  push:
    branches: [main]

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/www:latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}
            ghcr.io/${{ github.repository_owner }}/www:${{ github.sha }}

      - name: notify infra
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_PAT }}
          repository: ${{ github.repository_owner }}/www.infra
          event-type: deploy_www
          client-payload: |
            {
              "image": "ghcr.io/${{ github.repository_owner }}/www:${{ github.sha }}",
              "latest": "ghcr.io/${{ github.repository_owner }}/www:latest"
            }
